### PR TITLE
Add exposed Data Stories component

### PR DESCRIPTION
**Pull request by sandrahoang686**
Related Ticket: https://github.com/NASA-IMPACT/veda-ui/issues/1262
References @hanbyul-here original branch https://github.com/developmentseed/next-veda-ui/compare/main...stories-hub

### CODE REVIEW

**Review by dzole0311 — CHANGES_REQUESTED** [review]
When I visit the Data Catalog, I get: `Application error: a client-side exception has occurred (see the browser console for more information)`. It doesn't seem to happen in other deployments. Could we check why?

**Comment by vgeorge** [comment]
@dzole0311 this seems to be working well for me with the current version of Veda UI in the main branch (https://github.com/NASA-IMPACT/veda-ui/commit/7233df8bbb8212c9ed583ff0b08c1760ebd32ac0).

The steps I followed are:

- Set the head of my local veda-ui git repo to the commit above
- Ran `yarn buildlib` on that repo
- Changed package.json reference to my local folder ( `"@developmentseed/veda-ui": "file:/Users/vgeorge/dev/veda/config/.veda/ui",`)
- Start Next.js with mbtoken set
- Visited `/data-catalog`, `/exploration` and and `/stories` routes, none of them are broken

This is what I see at the stories page:

Screenshot 2024-11-28 at 12 24 08

**Comment by dzole0311** [comment]
Thanks for checking @vgeorge, I also can't reproduce it locally, but the error keeps being thrown the Netlify deployment url. I retriggered the build, but it keeps re-appearing. Looking into it.

**Comment by dzole0311** [comment]
Strange, Netlify kept an older deployment artifact which was trying to destructure the `navigate` prop that we don't use anymore. I had to publish a new UI version to bust the cache (clearing the cache through Netlify didn't work).

I think this is good to go now.

**Review by dzole0311 — APPROVED** [review]

**Pull request merged**
